name: gtfs_builder
channels:
  - conda-forge
  - anaconda
  - amauryval
dependencies:
  - python=3.9
  - flask=2.0.1
  - flask-cors=3.0.8
  - gunicorn=20.1.0
  - geolib=0.28.2
  - python-dotenv=0.15.0
  - matplotlib=3.4.3
  - descartes=1.1.0
  - datashader=0.13.0
  - holoviews=1.14.6