name: gtfs_builder
channels:
  - conda-forge
  - anaconda
  - amauryval
dependencies:
  - python=3.9
  - flask=2.1.2
  - flask-cors=3.0.8
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - geolib=0.28.8
  - pymongo=4.1.1
  - spatialpandas=0.4.3
  - python-dotenv=0.15.0